@startuml
left to right direction
actor Usuario
actor Miembro
actor Administrador
package gestion_de_fuentes{
(Crear fuente) as CU1
(Consultar fuente) as CU2
(Eliminar fuente) as CU3
(Modificar fuente) as CU4
(listar fuentes) as CU5
(Consultar fuente \npor nombre) as CUE1
(Consultar fuente \npor descripcion) as CUE2
(Consultar fuente \npor fechaRegistro) as CUE3
(Listar las fuentes \npor nombre) as CUE4
(Listar las fuentes \npor fechaRegistro) as CUE5
(Listar las fuentes \npor miembro) as CUE6
note right:Solo miembros creadores de familia
(Listar solo los nombres \nde las fuentes registradas) as CU7
(Listar las fuentes que \naportan mas ingresos) as CU8
(Consultar miembro) as CUE7
Miembro --> CU1
Miembro <-- CU2
Miembro --> CU3
Miembro --> CU4
Miembro <-- CU5
Miembro <-- CU8
' --
Administrador --> CU1
Administrador <-- CU2
Administrador --> CU3
Administrador --> CU4
Administrador <-- CU5
CU2 <|-- CUE1
CU2 <|-- CUE2
CU2 <|-- CUE3
CU5 <|-- CUE4
CU5 <|-- CUE5
CU5 <|-- CUE6
CU3 ..> CU2:include
CU4 ..> CU2:include
CUE6 ..> CUE7:include
Usuario --> CU7
}
@enduml
